name: linux

on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '42 2 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sumo_build: [ppa, nightly]
#        sumo_build: [ubuntu, ppa, nightly]

    steps:
    - name: Cloning Scenario
      uses: actions/checkout@v2

    - name: Preparing System
      if: matrix.sumo_build == 'ppa'
      run: sudo add-apt-repository ppa:sumo/stable

    - name: Installing SUMO from repo
      if: matrix.sumo_build != 'nightly'
      run: |
        sudo apt-get update
        sudo apt-get install sumo sumo-tools
        echo "SUMO_HOME=/usr/share/sumo" >> $GITHUB_ENV

    - name: Installing SUMO from PyPI
      if: matrix.sumo_build == 'nightly'
      run: |
        python -m pip install --index-url https://test.pypi.org/simple/ eclipse-sumo
        python -c "import sumo; print('SUMO_HOME=' + sumo.SUMO_HOME)" >> $GITHUB_ENV

    - name: Running Scenario
      run: |
        echo $SUMO_HOME; sumo  # just to check
        sumo -c scenario/InTAS_buildings.sumocfg -l sumo.log

    - name: Upload Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
          name: scenario-${{ matrix.sumo_build }}.log
          path: sumo.log
